### PR TITLE
187 update locks

### LINKED ISSUE #187: Review and improve locks in `Storage`
`RWLock` on `safe` does protect `active_blob` + `blobs` updates inside, so the `write` lock should be acquired only when these 2 fields updating. But if we look at `write_with_optional_meta` function, it is incorrectly acquire `write` lock (https://github.com/qoollo/pearl/blob/master/src/storage/core.rs#L313). It should acquire `read` lock, because it does not update neither `active_blob` nor `blobs` fields.
Same thing here: https://github.com/qoollo/pearl/blob/master/src/storage/core.rs#L890 and here: https://github.com/qoollo/pearl/blob/master/src/storage/core.rs#L912. Probably, there are more places where `write` lock taken incorrectly.

Also, it is strange that `blobs` protected with additional `RWLock`. In every places this lock acquired right after acquire of `RWLock` on `safe`, thus can be removed.

This incorrect locking mechanism results in significant performance degradation

### PR DESCRIPTION
**Pull request by idruzhitskiy**
Closes #187

### CODE REVIEW

File: src/blob/core.rs [hunk 1]
```diff
@@ -282,15 +289,17 @@ where
         }))
     }
 
-    pub(crate) async fn mark_all_as_deleted(&mut self, key: &K) -> Result<Option<u64>> {
-        if self.index.get_any(key).await?.is_some() {
-            let on_disk = self.index.on_disk();
+    pub(crate) async fn mark_all_as_deleted(blob: &ASRwLock<Self>, key: &K) -> Result<Option<u64>> {
```
Comment (ikopylov) [inline src/blob/core.rs:292]: The lock in the new implementation is acquired multiple times, which can lead to performance degradation. The original implementation was better. The only possible improvement here can be achieved by acquiring `upgradable_read` lock at first, then check key presence (`write.index.get_any(key).await?.is_some()`) and then upgrade to write lock if it is presented (any further lock manipulations should be avoided)

File: src/lib.rs [hunk 2]
```diff
@@ -46,6 +46,8 @@ extern crate anyhow;
 
 extern crate ring;
 
+extern crate async_std;
```
Comment (ikopylov) [inline src/lib.rs:49]: Why is it exported? Normally, this crate should be purely internal, as it is an implementation detail

File: src/storage/core.rs [hunk 3]
```diff
@@ -897,30 +901,33 @@ where
...
-        let total = entries_closed_blobs
-            .filter_map(|result| match result {
-                Ok(count) => count,
-                Err(error) => {
-                    warn!("failed to delete records: {}", error);
-                    None
+        let count = AtomicU64::new(0);
+        blobs
+            .for_each(|b| async {
+                let rwlock = ASRwLock::new(b);
```
Comment (ikopylov) [inline src/storage/core.rs:907]: Oh, it is not good to wrap blob with RwLock only in order to use the new signature of `Blob::mark_all_as_deleted`. I think, it is better just to revert to the original implementation, where `mark_all_as_deleted` just received `Blob` as `self`

File: src/blob/core.rs (hunk 1 above)
Comment (ikopylov) [reply src/blob/core.rs:292]: I just saw a removal implementation in `src/storage/core.rs`. I think, it is better just to revert to the original form of this function

File: src/storage/core.rs [hunk 4]
```diff
@@ -897,30 +901,33 @@ where
...
+                let result = Blob::mark_all_as_deleted(&rwlock, key).await;
+                match result {
+                    Ok(cnt) => {
+                        count.fetch_add(cnt.unwrap_or(0), Ordering::Release);
+                    }
+                    Err(err) => warn!("failed to delete records: {}", err),
```
Comment (ikopylov) [inline src/storage/core.rs:913]: Can you check why this error is not propagated above?

**Review by ikopylov — CHANGES_REQUESTED** [review]
Changes are required

File: src/storage/core.rs (hunk 4 above)
Comment (ikopylov) [reply src/storage/core.rs]: It would be good to return error to the Bob client if the error happened somewhere inside. But we should not stop processing other blobs if error happened in one

Comment (idruzhitskiy) [reply src/storage/core.rs]: Yep, error is returned if any blobs contained error, but processing is not stopped

File: src/filter/hierarchical.rs [hunk 5]
```diff
@@ -423,6 +436,26 @@ impl<Key, Filter, Child> HierarchicalFilters<Key, Filter, Child> {
...
     }
 
+    pub(crate) async fn for_each<F, R>(&mut self, f: F)
+    where
+        F: Fn(Child) -> R + Copy,
+        R: futures::Future<Output = Child>,
+    {
+        self.children = self
+            .children
+            .drain(..)
```
Comment (ikopylov) [inline src/filter/hierarchical.rs:446]: According to documentation `drain` will clear `children` collection. Looks like an error

File: src/filter/hierarchical.rs [hunk 6]
```diff
@@ -423,6 +436,26 @@ impl<Key, Filter, Child> HierarchicalFilters<Key, Filter, Child> {
...
+            .map(|o| async move {
+                if let Some(c) = o {
+                    Some(c.map_async(f).await)
+                } else {
+                    None
+                }
+            })
+            .collect::<FuturesUnordered<_>>()
+            .collect::<Vec<_>>()
```
Comment (ikopylov) [inline src/filter/hierarchical.rs:455]: The only place, where `for_each` is used just ignores the result of this function. So it is better to not collect results into a Vector

File: src/storage/core.rs [hunk 7]
```diff
@@ -897,29 +901,39 @@ where
...
-            .iter_mut()
-            .map(|b| b.mark_all_as_deleted(key))
-            .collect::<FuturesUnordered<_>>();
-        let total = entries_closed_blobs
-            .filter_map(|result| match result {
-                Ok(count) => count,
-                Err(error) => {
-                    warn!("failed to delete records: {}", error);
-                    None
+        let count = AtomicU64::new(0);
```
Comment (ikopylov) [inline src/storage/core.rs:904]: IMHO, original implementation of this function without Atomics was clearer and simpler

File: src/blob/core.rs [hunk 8]
```diff
@@ -229,11 +235,16 @@ where
         // @TODO implement
     }
 
-    pub(crate) async fn write(&mut self, mut record: Record) -> Result<()> {
+    pub(crate) async fn write(blob: &ASRwLock<Self>, record: Record) -> Result<()> {
+        debug!("blob write");
+        let blob = blob.upgradable_read().await;
```
Comment (ikopylov) [inline src/blob/core.rs:240]: Please, add comment that only one thread can acquire an `upgradable_read` lock. Because this is not obvious thing and the further code depends on this behavior (only one thread can write data at `self.current_offset`)

File: src/filter/hierarchical.rs (hunk 5 above)
Comment (idruzhitskiy) [reply src/filter/hierarchical.rs:446]: This is done to allow creation of futures from each of the values and processing it in parallel

File: src/filter/hierarchical.rs (hunk 6 above)
Comment (idruzhitskiy) [reply src/filter/hierarchical.rs:455]: This is needed to recreate source vector after parallel processing

File: src/filter/hierarchical.rs (hunk 5 above)
Comment (idruzhitskiy) [reply src/filter/hierarchical.rs:446]: We recreate leaves with the new data

File: src/storage/core.rs (hunk 7 above)
Comment (idruzhitskiy) [reply src/storage/core.rs:904]: You right, since we don't need ownership here I'll return old function

File: src/filter/hierarchical.rs (hunk 6 above)
Comment (idruzhitskiy) [reply src/filter/hierarchical.rs:455]: Function removed

File: src/filter/hierarchical.rs (hunk 5 above)
Comment (idruzhitskiy) [reply src/filter/hierarchical.rs:446]: This was to allow for ownership transfer into closure. Now function is removed

File: CHANGELOG.md [hunk 9]
```diff
@@ -31,6 +31,7 @@ Pearl changelog
 - Returning error when validating blob with corrupted records (#180)
 
 #### Updated
+- Update locks (#187)
```
Comment (ikopylov) [inline CHANGELOG.md:34]: Please, move this line to `[Unreleased]` section

**Review by ikopylov — APPROVED** [review]
LGTM
