### PR TITLE
Observer worker never stops bug fix, improve Arc placement and visibility levels

### LINKED ISSUE #185: Review and update `Arc` placement in `Storage`
Looks like only `inner` should be wrapped in `Arc` (https://github.com/qoollo/pearl/blob/master/src/storage/core.rs#L43), because it is actually passed outside. All inner fields like `safe`, `next_blob_id`, `blobs` does not pass outside (from the first glance), so it looks like `Arc` on them can be safely removed

### LINKED ISSUE #186: Review and update visibility levels in `Storage`
Too many unnecessary `pub(crate)` usage (https://github.com/qoollo/pearl/blob/master/src/storage/core.rs).
Looks like `ioring` should be totally private (https://github.com/qoollo/pearl/blob/master/src/storage/core.rs#L55)
`config` and `safe` can have readonly access, so they should be exposed through the getter and declared as private (https://github.com/qoollo/pearl/blob/master/src/storage/core.rs#L52).
Same for fields of `Safe`: they should not be available for updated outside (https://github.com/qoollo/pearl/blob/master/src/storage/core.rs#L63). From the architecture point of view, `Safe` should not visible at all, because it is an integral part of `Inner<K>` protected by lock (this is discussable).

### LINKED ISSUE #259: ObserverWorker never stops due to loopback sender
`loopback_sender` prevents stopping of `ObserverWorker`. That leads to memory leak

### PR DESCRIPTION
**Pull request by ikopylov**
Closes #259 
Closes #185 
Closes #186

### CODE REVIEW

File: src/storage/observer_worker.rs [hunk 1]
```diff
@@ -1,147 +1,218 @@
...
+                self.process_msg(msg).await?;
+                Ok(TickResult::Continue)
+            },
+            None => Ok(TickResult::Stop)
+        }
+    }
+
+    async fn tick_with_deadline(&mut self, deadline: Instant) -> Result<TickResult> {
+        // Extend deadline a little bit to guaranty, that process_defered will detect exceeding
+        let deadline = deadline + Duration::from_millis(10);
```
Comment (idruzhitskiy) [inline src/storage/observer_worker.rs:91]: Shouldn't this duration depend on config's defered min/max time?

Comment (ikopylov) [reply src/storage/observer_worker.rs:91]: Yes, the `deadline` is updated in `deffer_blob_indexes_dump` and in `process_deferred_blob_index_dump` according to  deferred min/max time from config.

The idea of this change is to update the `deadline`, every time `DeferredDumpBlobIndexes` message income and on every loop, when deadline is not `None` runs `recv` with additional timeout. If timeout triggered, run processing of deferred index dump and reset `deadline` value to `None.

Comment (idruzhitskiy) [reply src/storage/observer_worker.rs:91]: But `Duration::from_millis(10)` does not depend on config values, and therefore can be too large/too small in some situations, if I understood correctly

Comment (ikopylov) [reply src/storage/observer_worker.rs:91]: The idea is to set the duration a little longer than the original one, so that the check in `process_deferred_blob_index_dump` is guaranteed to be successful.

> But Duration::from_millis(10) does not depend on config values, and therefore can be too large/too small in some situations, if I understood correctly

The original concept of deferred execution is that the processing will happen at some time later. If it happens an additional 10ms later, this is not critical. The initial values in the config are measured in minutes.

Actually, I think, it would be good to reduce `10ms` to `1ms`

**Comment by idruzhitskiy** [comment]
LGTM
