### PR TITLE
289 validate on index regeneration

### LINKED ISSUE #289: Index regeneration on a corrupted BLOB creates an invalid index instead of returning an error
`brt` shows this output on BLOB validation:
```
[root@bob-9 ~]# brt validate-blob -p /opt/disk9/bob/554/1685577600_8hklJQ6f0R/
[2023-06-06T12:56:39Z INFO  brt] Logger initialized
[2023-06-06T12:56:39Z INFO  brt::blob_recovery_tool::utils] Start validation
[2023-06-06T12:57:01Z WARN  brt::blob_recovery_tool::readers] Record read error, trying read next record: record header validation error: record header magic byte is invalid
[2023-06-06T12:57:01Z ERROR brt::blob_recovery_tool::utils] [/opt/disk9/bob/554/1685577600_8hklJQ6f0R/bob_8hklJQ6f0R.0.blob] validation error: record header validation error: record header magic byte is invalid
[2023-06-06T12:57:01Z INFO  brt::blob_recovery_tool::utils] 1 files validated
[2023-06-06T12:57:01Z INFO  brt::blob_recovery_tool::utils] Validation completed! 1 files validated
[2023-06-06T12:57:01Z INFO  brt::blob_recovery_tool::utils] Print corrupted blob files
/opt/disk9/bob/554/1685577600_8hklJQ6f0R/bob_8hklJQ6f0R.0.blob
```

This is on Bob v2.0.0

### PR DESCRIPTION
**Pull request by idruzhitskiy**
Closes #289

### CODE REVIEW

File: tests/tests.rs [hunk 1]
```diff
@@ -429,6 +429,59 @@ async fn test_corrupted_index_regeneration() {
...
+    ];
+    let len = corruptions.len();
+
+    for (i, corruption) in corruptions.into_iter().enumerate() {
+        let blob_file_path = path.join(format!("test.{i}.blob"));
+        let index_file_path = path.join(format!("test.{i}.index"));
+        assert!(blob_file_path.exists());
+        assert!(index_file_path.exists());
+
+        common::corrupt_file(blob_file_path, corruption).expect("blob corruption failed");
```
Comment (ikopylov) [inline tests/tests.rs:465]: This is a bad test, because several corruptions are applied at once in different places. This test would have passed even without changes, because blob header corruption worked properly before.
The proper way to implement this test is to create the storage, apply one corruption type, then verify, that the corruption was detected, and clean-up storage at the end.

File: tests/tests.rs [hunk 2]
```diff
@@ -429,6 +429,59 @@ async fn test_corrupted_index_regeneration() {
...
+        std::fs::remove_file(index_file_path.clone()).expect("index removal");
+    }
+    let new_storage = common::create_test_storage(&path, 1_000_000)
+        .await
+        .expect("storage should be loaded successfully");
```
Comment (ikopylov) [inline tests/tests.rs:470]: Verify also, that `corrupted_blobs_count == 1`

File: tests/tests.rs [hunk 3]
```diff
@@ -429,6 +429,49 @@ async fn test_corrupted_index_regeneration() {
...
+    use std::mem::size_of;
+    use common::CorruptionType;
+
+    let now = Instant::now();
+    let path = common::init("corrupted_blob_index");
+    let storage = common::create_test_storage(&path, 70_000).await.unwrap();
+    let records = common::generate_records(100, 10_000);
+    for (i, data) in &records {
+        write_one(&storage, *i, data, None).await.unwrap();
+        sleep(Duration::from_millis(10)).await;
```
Comment (ikopylov) [inline tests/tests.rs:443]: Why did you add this sleep?

File: tests/tests.rs [hunk 4]
```diff
@@ -429,6 +429,49 @@ async fn test_corrupted_index_regeneration() {
...
+    std::fs::remove_file(index_file_path.clone()).expect("index removal");
+    let new_storage = common::create_test_storage(&path, 1_000_000)
+        .await
+        .expect("storage should be loaded successfully");
+    new_storage.close().await.unwrap();
+
+    let index_file_path = path.join("test.0.index");
+    assert!(!index_file_path.exists());
+
+    let new_storage = common::create_test_storage(&path, 1_000_000)
```
Comment (ikopylov) [inline tests/tests.rs:466]: I think, there is no need to create a storage one more time just to check `new_storage.corrupted_blobs_count()` value. It should be `1` already on the second storage creation (right after the corruption was made)

File: tests/tests.rs (hunk 3 above)
Comment (idruzhitskiy) [reply tests/tests.rs:443]: Left from other test, removed

**Review by ikopylov — APPROVED** [review]
LGTM
