### PR TITLE
177 fix docs

### LINKED ISSUE #177: Actualize documentation

### PR DESCRIPTION
**Pull request by idruzhitskiy**
Closes #177

### CODE REVIEW

**Comment by ikopylov** [comment]
It's strange, but this PR somehow breaks the tests.

Additionally, there are new warnings from docs. Can you fix them?

**Comment by idruzhitskiy** [comment]
> this PR somehow breaks the tests.

Actually `cargo test` compiles `doctests`, which are tests from docs.

File: src/storage/core.rs [hunk 1]
```diff
@@ -235,11 +235,14 @@ where
...
-    /// ```no-run
+    /// ```no_run
+    /// use pearl::{Builder, Storage, UnitKey};
+    ///
     /// async fn write_data() {
-    ///     let key = 42u64.to_be_bytes().to_vec();
+    ///     let key = UnitKey::default();
     ///     let data = b"async written to blob".to_vec();
-    ///     storage.write(key, data).await
+    ///     let storage: Storage<UnitKey> = Builder::new().build().unwrap();
```
Comment (ikopylov) [inline src/storage/core.rs:244]: I think `storage` could be an argument of the function. In this way it will be a little bit more practical example

File: src/storage/core.rs [hunk 2]
```diff
@@ -252,13 +255,16 @@ where
...
+    /// ```no_run
+    /// use pearl::{Builder, Meta, Storage, UnitKey};
+    ///
     /// async fn write_data() {
-    ///     let key = 42u64.to_be_bytes().to_vec();
+    ///     let key = UnitKey::default();
     ///     let data = b"async written to blob".to_vec();
-    ///     let meta = Meta::new();
+    ///     let mut meta = Meta::new();
+    ///     let storage: Storage<UnitKey> = Builder::new().build().unwrap();
```
Comment (ikopylov) [inline src/storage/core.rs:265]: Same here

File: src/storage/core.rs [hunk 3]
```diff
@@ -361,9 +367,12 @@ where
...
     /// Reads the first found data matching given key.
     /// # Examples
-    /// ```no-run
+    /// ```no_run
+    /// use pearl::{Builder, Meta, Storage, UnitKey};
+    ///
     /// async fn read_data() {
-    ///     let key = 42u64.to_be_bytes().to_vec();
+    ///     let key = UnitKey::default();
+    ///     let storage: Storage<UnitKey> = Builder::new().build().unwrap();
```
Comment (ikopylov) [inline src/storage/core.rs:375]: And here

File: src/storage/core.rs [hunk 4]
```diff
@@ -1220,3 +1234,71 @@ where
         active + closed
     }
 }
+
+/// Key for demonstration purposes
+#[derive(Debug, Clone, PartialEq, Eq)]
+pub struct UnitKey(Vec<u8>);
```
Comment (ikopylov) [inline src/storage/core.rs:1240]: Is it possible to make it private (without `pub`)?

Comment (idruzhitskiy) [reply src/storage/core.rs:1234]: No. Code examples must use public entities from crate

File: src/storage/core.rs [hunk 5]
```diff
@@ -1220,3 +1228,71 @@ where
...
+
+impl From<Vec<u8>> for UnitKey {
+    fn from(v: Vec<u8>) -> Self {
+        Self(v)
+    }
+}
+
+impl PartialOrd for UnitKey {
+    fn partial_cmp(&self, _: &Self) -> Option<CmpOrdering> {
+        Some(CmpOrdering::Equal)
```
Comment (ikopylov) [inline src/storage/core.rs:1262]: Just in case: can you implement trivial, but working key comaprison?

Comment (ikopylov) [reply src/storage/core.rs:1262]: Moreover, I think it is good idea to move `Key`, `RefKey` traits and this `UnitKey` into separate file and make `UnitKey` more universal (add generic parameter, that specifies key size)

File: src/storage/key.rs [hunk 6]
```diff
@@ -0,0 +1,94 @@
...
+        Self::Ref::from(self.as_ref())
+    }
+}
+
+/// Trait for reference key type
+pub trait RefKey<'a>: Ord + From<&'a [u8]> {}
+
+/// Key for demonstration purposes
+#[derive(Debug, Clone, PartialEq, Eq)]
+pub struct VectorKey(Vec<u8>);
```
Comment (ikopylov) [inline src/storage/key.rs:30]: Maybe we can implement `VectorKey` with constant generic parameter to specify size?
```
pub struct VectorKey<const N: usize>(Vec<u8>);
```

**Review by ikopylov — APPROVED** [review]
LGTM
